/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Levels.HelpWindows;

import MainPackage.QueryExecuter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author thom
 */
public class NewAppointment extends javax.swing.JFrame {
    /**
     * Creates new form NewAppointment
     */
    public NewAppointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FirstnameTextfield = new javax.swing.JTextField();
        LastnameTextfield = new javax.swing.JTextField();
        AppDateTextfield = new javax.swing.JTextField();
        AppTimeTextfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NewAppWarning = new javax.swing.JLabel();
        SubmitAppButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Appointment");

        jLabel1.setText("Create New Appointment");

        FirstnameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameTextfieldActionPerformed(evt);
            }
        });

        LastnameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameTextfieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Patient First Name :");

        jLabel3.setText("Patient Last Name :");

        jLabel4.setText("Appointment Date :");

        jLabel5.setText("Appointment Time :");

        NewAppWarning.setText("Enter Appointment Information");

        SubmitAppButton.setText("Submit");
        SubmitAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitAppButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("YYYY-MM-DD");

        jLabel7.setText("HH:MM:SS");

        ExitButton.setText("EXIT");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(NewAppWarning))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addComponent(SubmitAppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(AppTimeTextfield)
                                .addComponent(AppDateTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LastnameTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(FirstnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AppDateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AppTimeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(NewAppWarning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SubmitAppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitButton)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstnameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameTextfieldActionPerformed

    private void LastnameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameTextfieldActionPerformed

    private void SubmitAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitAppButtonActionPerformed
        String fname = FirstnameTextfield.getText();
        String lname = LastnameTextfield.getText();
        String appDate = AppDateTextfield.getText();
        String appTime = AppTimeTextfield.getText();
        
        if(fname == null || lname == null || appDate == null || appTime == null){
            NewAppWarning.setText("One or more TextFields are empty");
        }
        else{
            String nameQuery = "SELECT PatientID, FirstName, LastName, PrimaryPhysician FROM Patients WHERE FirstName = '" + fname + "' AND LastName = '" + lname + "';";
            ResultSet rs = QueryExecuter.runQuery(nameQuery);
            
            try {
                if (!rs.isBeforeFirst() ) {
                    NewAppWarning.setText("Patient Not Found"); 
                }
                else{
                    int physicianId = 0;
                    int patientId = 0;
                    while(rs.next()){
                        physicianId = rs.getInt("PrimaryPhysician");
                        patientId = rs.getInt("PatientId");
                    }
                    String newAppQuery = "INSERT into Appointments(AppointmentTime, AppointmentDate, AppointmentComplete)\n" +
                                         "VALUES('" + appTime + "' , '" + appDate + "', 'No');";
                    QueryExecuter.runUpdate(newAppQuery);
                    
                    String getNewAppId = "SELECT AppointmentID \n" +
                                         "FROM Appointments\n" +
                                         "WHERE AppointmentDate = '" + appDate + "' AND AppointmentTime = '" + appTime + "';";
                    
                    ResultSet appRs = QueryExecuter.runQuery(getNewAppId);
                    int newAppId = 0;
                    while(appRs.next()){
                        newAppId = appRs.getInt("AppointmentID");
                    }
                    
                    String insertAppLine = "INSERT into AppointmentLine(AppointmentID, StaffID, PatientID)\n" +
                                           "VALUES(" + newAppId + ", " + physicianId + ", " + patientId + ");";
                    QueryExecuter.runUpdate(insertAppLine);
                    setVisible(false);
                    dispose();
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(NewAppointment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_SubmitAppButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AppDateTextfield;
    private javax.swing.JTextField AppTimeTextfield;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField FirstnameTextfield;
    private javax.swing.JTextField LastnameTextfield;
    private javax.swing.JLabel NewAppWarning;
    private javax.swing.JButton SubmitAppButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
