/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Levels;

import Levels.HelpWindows.AddIllness;
import Levels.HelpWindows.AddSymptom;
import Levels.HelpWindows.NewAppointment;
import MainPackage.HelperFunctions;
import Models.Appointment;
import Models.Employee;
import Models.Medical;
import Models.Patient;
import java.awt.event.MouseListener;
import javax.swing.DefaultListModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author thom
 */
public class LevelTwo extends javax.swing.JInternalFrame {
    int PatientSelected;
    Employee emp;
    /**
     * Creates new form LevelTwoIllness
     * @param signEmp
     */
    public LevelTwo(Employee signEmp) {
        emp = signEmp;
        
        //make frame immovable
        BasicInternalFrameUI bifui = ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()); 
        for(MouseListener listener : bifui.getNorthPane().getMouseListeners()){
            bifui.getNorthPane().removeMouseListener(listener);
        }
        
        initComponents();
        myComponents();
    }
    
    private void myComponents(){
        UserInfo.setText("User: " + emp.getName());
        setAppointmentList();
        setPatientList();
    }
    
    private void setPatientList(){
        String[] patients = Employee.getPatients(emp.getId());
        HelperFunctions.fillList(patients, PatientsList);
    }
    
    private void setAppointmentList(){
        String[] apps = Appointment.getPhysApps(emp.getId());
        HelperFunctions.fillList(apps, AppointmentList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatientsList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AppointmentList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        IllnessList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        SymptomsList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        MedicationPane = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        AllergiesPane = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        RelatedPane = new javax.swing.JTextPane();
        AddMedicationButton = new javax.swing.JButton();
        AddAllergyButton = new javax.swing.JButton();
        AddIllnessButton = new javax.swing.JButton();
        AddSymptomButton = new javax.swing.JButton();
        NewAppButton = new javax.swing.JButton();
        MedicationTextField = new javax.swing.JTextField();
        AllergyTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LogoutButton = new javax.swing.JMenuItem();
        ClockInButton = new javax.swing.JMenuItem();
        ClockOutButton = new javax.swing.JMenuItem();

        setBackground(new java.awt.Color(142, 142, 142));
        setPreferredSize(new java.awt.Dimension(1110, 560));

        UserInfo.setText("USER: ");
        UserInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PatientsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                PatientsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(PatientsList);

        jLabel2.setText("YOUR PATIENTS");

        jScrollPane2.setViewportView(AppointmentList);

        jLabel3.setText("YOUR APPOINTMENTS");

        IllnessList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                IllnessListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(IllnessList);

        SymptomsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                SymptomsListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(SymptomsList);

        jLabel4.setText("Illnesses");

        jLabel5.setText("Symptoms");

        jLabel6.setText("Related");

        jLabel1.setText("Medications");

        jLabel7.setText("Allergies");

        MedicationPane.setBackground(new java.awt.Color(254, 254, 254));
        jScrollPane8.setViewportView(MedicationPane);

        AllergiesPane.setBackground(new java.awt.Color(254, 254, 254));
        jScrollPane9.setViewportView(AllergiesPane);

        jScrollPane6.setViewportView(RelatedPane);

        AddMedicationButton.setText("Add Medication");
        AddMedicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMedicationButtonActionPerformed(evt);
            }
        });

        AddAllergyButton.setText("Add Allergy");
        AddAllergyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAllergyButtonActionPerformed(evt);
            }
        });

        AddIllnessButton.setText("Add Illness");
        AddIllnessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIllnessButtonActionPerformed(evt);
            }
        });

        AddSymptomButton.setText("Add Symptom");
        AddSymptomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSymptomButtonActionPerformed(evt);
            }
        });

        NewAppButton.setText("New Appointment");
        NewAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAppButtonActionPerformed(evt);
            }
        });

        AllergyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllergyTextFieldActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        jMenu1.add(LogoutButton);

        ClockInButton.setText("Clock In");
        ClockInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClockInButtonActionPerformed(evt);
            }
        });
        jMenu1.add(ClockInButton);

        ClockOutButton.setText("Clock Out");
        ClockOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClockOutButtonActionPerformed(evt);
            }
        });
        jMenu1.add(ClockOutButton);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(UserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AddMedicationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                .addComponent(AddAllergyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddSymptomButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MedicationTextField)
                                .addComponent(AllergyTextField))
                            .addComponent(AddIllnessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(NewAppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(NewAppButton))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(UserInfo)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(AddMedicationButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MedicationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(AddAllergyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AllergyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(AddIllnessButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddSymptomButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane6))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ClockInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClockInButtonActionPerformed
        emp.ClockIn();
    }//GEN-LAST:event_ClockInButtonActionPerformed

    private void ClockOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClockOutButtonActionPerformed
        emp.ClockOut();
    }//GEN-LAST:event_ClockOutButtonActionPerformed

    private void PatientsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_PatientsListValueChanged
        //get info from selected appointment and change app info pane
        String patId = PatientsList.getSelectedValue();
        int id = HelperFunctions.getIdValue(patId, 0, null);
        if(id != -1){
            String[] pInfo = Patient.getPatientInfo(id);
            MedicationPane.setText(pInfo[2]);
            AllergiesPane.setText(pInfo[3]);
            DefaultListModel dlm = new DefaultListModel();
            dlm.addElement(pInfo[0]);
            IllnessList.setModel(dlm);
            DefaultListModel dlm2 = new DefaultListModel();
            dlm2.addElement(pInfo[1]);
            SymptomsList.setModel(dlm2);
            
        }
    }//GEN-LAST:event_PatientsListValueChanged

    private void IllnessListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_IllnessListValueChanged
        SymptomsList.clearSelection();
        String illnessName = IllnessList.getSelectedValue();
        RelatedPane.setText(Medical.getSymptoms(illnessName));
    }//GEN-LAST:event_IllnessListValueChanged

    private void SymptomsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_SymptomsListValueChanged
        IllnessList.clearSelection();
        String symptomName = SymptomsList.getSelectedValue();
        RelatedPane.setText(Medical.getIllnesses(symptomName));
    }//GEN-LAST:event_SymptomsListValueChanged

    private void AddMedicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMedicationButtonActionPerformed
        String patId = PatientsList.getSelectedValue();
        int id = HelperFunctions.getIdValue(patId, 0, null);
        if(id != -1){
            Medical.addMedication(id, MedicationTextField.getText());
        }
    }//GEN-LAST:event_AddMedicationButtonActionPerformed

    private void AddAllergyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAllergyButtonActionPerformed
        String patId = PatientsList.getSelectedValue();
        int id = HelperFunctions.getIdValue(patId, 0, null);
        if(id != -1){
            Medical.addAllergy(id, AllergyTextField.getText());
        }
    }//GEN-LAST:event_AddAllergyButtonActionPerformed

    private void AddIllnessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIllnessButtonActionPerformed
        String patId = PatientsList.getSelectedValue();
        int id = HelperFunctions.getIdValue(patId, 0, null);
        if(id != -1){
            new AddIllness(id).setVisible(true);
        }
    }//GEN-LAST:event_AddIllnessButtonActionPerformed

    private void AddSymptomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSymptomButtonActionPerformed
        String patId = PatientsList.getSelectedValue();
        int id = HelperFunctions.getIdValue(patId, 0, null);
        if(id != -1){
            new AddSymptom(id).setVisible(true);
        }
    }//GEN-LAST:event_AddSymptomButtonActionPerformed

    private void NewAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAppButtonActionPerformed
         new NewAppointment().setVisible(true);
    }//GEN-LAST:event_NewAppButtonActionPerformed

    private void AllergyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllergyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AllergyTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAllergyButton;
    private javax.swing.JButton AddIllnessButton;
    private javax.swing.JButton AddMedicationButton;
    private javax.swing.JButton AddSymptomButton;
    private javax.swing.JTextPane AllergiesPane;
    private javax.swing.JTextField AllergyTextField;
    private javax.swing.JList<String> AppointmentList;
    private javax.swing.JMenuItem ClockInButton;
    private javax.swing.JMenuItem ClockOutButton;
    private javax.swing.JList<String> IllnessList;
    private javax.swing.JMenuItem LogoutButton;
    private javax.swing.JTextPane MedicationPane;
    private javax.swing.JTextField MedicationTextField;
    private javax.swing.JButton NewAppButton;
    private javax.swing.JList<String> PatientsList;
    private javax.swing.JTextPane RelatedPane;
    private javax.swing.JList<String> SymptomsList;
    private javax.swing.JLabel UserInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
