package Levels;

import MainPackage.QueryExecuter;
import java.sql.ResultSet;
import static MainPackage.Login.con;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author thom
 */
public class LevelThree extends javax.swing.JInternalFrame {

    /**
     * Creates new form LevelThree
     */
    public LevelThree(int level) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    static DefaultTableModel patientModel;
    static DefaultTableModel employeeModel;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPaneMainWindow = new javax.swing.JLayeredPane();
        jPanelWelcome = new javax.swing.JPanel();
        jPanelAddPatient = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        textAddLastName1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textAddFirstName1 = new javax.swing.JTextField();
        textAddAllergies = new javax.swing.JTextField();
        textAddMedications = new javax.swing.JTextField();
        textAddPhysician = new javax.swing.JTextField();
        btnSavePatient = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        textAddAge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textAddGender = new javax.swing.JTextField();
        jPanelPatients = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PatientTable = new javax.swing.JTable();
        btnDeletePatient = new javax.swing.JButton();
        btnAddPatient = new javax.swing.JButton();
        jPanelAddEmployee = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textAddLastName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textAddFirstName = new javax.swing.JTextField();
        textAddTitle = new javax.swing.JTextField();
        textAddLevel = new javax.swing.JTextField();
        textAddUsername = new javax.swing.JTextField();
        btnSaveUser = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        textAddPassword = new javax.swing.JPasswordField();
        textAddEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanelDirectory = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        btnEmployeeAdd = new javax.swing.JButton();
        btnEmployeeRemove = new javax.swing.JButton();
        jPanelTerminal = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textTerminal = new javax.swing.JTextArea();
        btnRunTerminal = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanelBtns = new javax.swing.JPanel();
        btnPatients = new javax.swing.JButton();
        btnDirectory = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnFile = new javax.swing.JMenu();
        btnLogout = new javax.swing.JMenuItem();
        btnCloseAll = new javax.swing.JMenuItem();
        btnMenuCheckIn = new javax.swing.JMenuItem();
        btnMenuCheckout = new javax.swing.JMenuItem();
        btnExit = new javax.swing.JMenuItem();
        btnEdit = new javax.swing.JMenu();
        btnMenuTerminal = new javax.swing.JMenuItem();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPaneMainWindow.setBackground(new java.awt.Color(255, 51, 51));
        jLayeredPaneMainWindow.setLayout(new java.awt.CardLayout());

        jPanelAddEmployee.setVisible(false);
        jPanelWelcome.setBackground(new java.awt.Color(204, 204, 204));
        jPanelWelcome.setEnabled(false);

        javax.swing.GroupLayout jPanelWelcomeLayout = new javax.swing.GroupLayout(jPanelWelcome);
        jPanelWelcome.setLayout(jPanelWelcomeLayout);
        jPanelWelcomeLayout.setHorizontalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        jPanelWelcomeLayout.setVerticalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        jLayeredPaneMainWindow.add(jPanelWelcome, "card3");

        jPanelAddEmployee.setVisible(false);
        jPanelAddPatient.setBackground(new java.awt.Color(204, 204, 204));
        jPanelAddPatient.setEnabled(false);

        jLabel5.setText("Last Name");

        textAddLastName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddLastName1ActionPerformed(evt);
            }
        });

        jLabel9.setText("First Name");

        jLabel10.setText("Allergies");

        jLabel11.setText("Medications");

        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel24.setText("New Patient");

        jLabel12.setText("Physician");

        textAddFirstName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddFirstName1ActionPerformed(evt);
            }
        });

        textAddAllergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddAllergiesActionPerformed(evt);
            }
        });

        textAddMedications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddMedicationsActionPerformed(evt);
            }
        });

        textAddPhysician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddPhysicianActionPerformed(evt);
            }
        });

        btnSavePatient.setText("Save");
        btnSavePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePatientActionPerformed(evt);
            }
        });

        jLabel13.setText("Gender");

        jLabel14.setText("Age");

        textAddGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddGenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddPatientLayout = new javax.swing.GroupLayout(jPanelAddPatient);
        jPanelAddPatient.setLayout(jPanelAddPatientLayout);
        jPanelAddPatientLayout.setHorizontalGroup(
            jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddPatientLayout.createSequentialGroup()
                .addGroup(jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddPatientLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(52, 52, 52)
                        .addGroup(jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textAddFirstName1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(textAddLastName1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(textAddAllergies, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(textAddMedications, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(textAddPhysician, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(textAddAge)
                            .addComponent(textAddGender))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelAddPatientLayout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(642, 642, 642)
                        .addComponent(jButton3)))
                .addContainerGap())
            .addGroup(jPanelAddPatientLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(btnSavePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddPatientLayout.setVerticalGroup(
            jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddPatientLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddPatientLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textAddLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textAddFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textAddAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAddMedications, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(16, 16, 16)
                .addGroup(jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAddPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAddAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(20, 20, 20)
                .addGroup(jPanelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textAddGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnSavePatient)
                .addGap(49, 49, 49))
        );

        jLayeredPaneMainWindow.add(jPanelAddPatient, "card3");

        jPanelAddEmployee.setVisible(false);
        jPanelPatients.setBackground(new java.awt.Color(204, 204, 204));
        jPanelPatients.setEnabled(false);

        jButton7.setText("X");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel47.setText("Patients");

        PatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "First", "Last", "Allergies", "Medications", "Primary Physician", "Age", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PatientTable);

        btnDeletePatient.setText("Delete");
        btnDeletePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePatientActionPerformed(evt);
            }
        });

        btnAddPatient.setText("Add");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPatientsLayout = new javax.swing.GroupLayout(jPanelPatients);
        jPanelPatients.setLayout(jPanelPatientsLayout);
        jPanelPatientsLayout.setHorizontalGroup(
            jPanelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPatientsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPatientsLayout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addGroup(jPanelPatientsLayout.createSequentialGroup()
                        .addGroup(jPanelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeletePatient, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPatientsLayout.setVerticalGroup(
            jPanelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPatientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPatientsLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddPatient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletePatient)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelPatientsLayout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)))
                .addGap(64, 64, 64))
        );

        jLayeredPaneMainWindow.add(jPanelPatients, "card3");

        jPanelAddEmployee.setVisible(false);
        jPanelAddEmployee.setBackground(new java.awt.Color(204, 204, 204));
        jPanelAddEmployee.setEnabled(false);

        jLabel1.setText("Last Name");

        textAddLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddLastNameActionPerformed(evt);
            }
        });

        jLabel2.setText("First Name");

        jLabel3.setText("Title");

        jLabel6.setText("Level");

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setText("New Employee");

        jLabel7.setText("Username");

        textAddFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddFirstNameActionPerformed(evt);
            }
        });

        textAddTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddTitleActionPerformed(evt);
            }
        });

        textAddLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddLevelActionPerformed(evt);
            }
        });

        textAddUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddUsernameActionPerformed(evt);
            }
        });

        btnSaveUser.setText("Save");
        btnSaveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUserActionPerformed(evt);
            }
        });

        jLabel8.setText("Password");

        jLabel4.setText("Email");

        javax.swing.GroupLayout jPanelAddEmployeeLayout = new javax.swing.GroupLayout(jPanelAddEmployee);
        jPanelAddEmployee.setLayout(jPanelAddEmployeeLayout);
        jPanelAddEmployeeLayout.setHorizontalGroup(
            jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddEmployeeLayout.createSequentialGroup()
                .addGroup(jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddEmployeeLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(52, 52, 52)
                        .addGroup(jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textAddFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(textAddLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(textAddTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(textAddLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(textAddUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(textAddPassword)
                            .addComponent(textAddEmail))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelAddEmployeeLayout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(642, 642, 642)
                        .addComponent(jButton2)))
                .addContainerGap())
            .addGroup(jPanelAddEmployeeLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(btnSaveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddEmployeeLayout.setVerticalGroup(
            jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddEmployeeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textAddLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textAddFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAddLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16)
                .addGroup(jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAddUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAddEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(textAddPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnSaveUser)
                .addGap(49, 49, 49))
        );

        jLayeredPaneMainWindow.add(jPanelAddEmployee, "card3");

        jPanelAddEmployee.setVisible(false);
        jPanelDirectory.setBackground(new java.awt.Color(204, 204, 204));
        jPanelDirectory.setEnabled(false);

        jButton6.setText("X");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel31.setText("Directory");

        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "First", "Last", "Signed In", "Title", "Level", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(EmployeeTable);

        btnEmployeeAdd.setText("Add");
        btnEmployeeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeAddActionPerformed(evt);
            }
        });

        btnEmployeeRemove.setText("Delete");
        btnEmployeeRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDirectoryLayout = new javax.swing.GroupLayout(jPanelDirectory);
        jPanelDirectory.setLayout(jPanelDirectoryLayout);
        jPanelDirectoryLayout.setHorizontalGroup(
            jPanelDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDirectoryLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanelDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDirectoryLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addContainerGap())
                    .addGroup(jPanelDirectoryLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEmployeeAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(btnEmployeeRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelDirectoryLayout.setVerticalGroup(
            jPanelDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDirectoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDirectoryLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(16, 16, 16)
                        .addComponent(btnEmployeeAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmployeeRemove))
                    .addGroup(jPanelDirectoryLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jLayeredPaneMainWindow.add(jPanelDirectory, "card3");

        jPanelAddEmployee.setVisible(false);
        jPanelTerminal.setBackground(new java.awt.Color(204, 204, 204));
        jPanelTerminal.setEnabled(false);

        jButton8.setText("X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel39.setText("SQL Terminal");

        textTerminal.setColumns(20);
        textTerminal.setRows(5);
        jScrollPane3.setViewportView(textTerminal);

        btnRunTerminal.setText("Run");
        btnRunTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunTerminalActionPerformed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTerminalLayout = new javax.swing.GroupLayout(jPanelTerminal);
        jPanelTerminal.setLayout(jPanelTerminalLayout);
        jPanelTerminalLayout.setHorizontalGroup(
            jPanelTerminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTerminalLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanelTerminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTerminalLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelTerminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRunTerminal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPanelTerminalLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)))
                .addContainerGap())
        );
        jPanelTerminalLayout.setVerticalGroup(
            jPanelTerminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTerminalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTerminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(jPanelTerminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTerminalLayout.createSequentialGroup()
                        .addComponent(btnRunTerminal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jLayeredPaneMainWindow.add(jPanelTerminal, "card3");

        btnPatients.setText("Patients");
        btnPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientsActionPerformed(evt);
            }
        });

        btnDirectory.setText("Directory");
        btnDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnsLayout = new javax.swing.GroupLayout(jPanelBtns);
        jPanelBtns.setLayout(jPanelBtnsLayout);
        jPanelBtnsLayout.setHorizontalGroup(
            jPanelBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPatients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDirectory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBtnsLayout.setVerticalGroup(
            jPanelBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnsLayout.createSequentialGroup()
                .addComponent(btnPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 862, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(111, Short.MAX_VALUE)
                    .addComponent(jLayeredPaneMainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPaneMainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        btnFile.setText("File");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        btnFile.add(btnLogout);

        btnCloseAll.setText("Close All");
        btnCloseAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAllActionPerformed(evt);
            }
        });
        btnFile.add(btnCloseAll);

        btnMenuCheckIn.setText("Check In");
        btnFile.add(btnMenuCheckIn);

        btnMenuCheckout.setText("Check Out");
        btnMenuCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCheckoutActionPerformed(evt);
            }
        });
        btnFile.add(btnMenuCheckout);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        btnFile.add(btnExit);

        jMenuBar1.add(btnFile);

        btnEdit.setText("Edit");

        btnMenuTerminal.setText("Terminal");
        btnMenuTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuTerminalActionPerformed(evt);
            }
        });
        btnEdit.add(btnMenuTerminal);

        jMenuBar1.add(btnEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void textAddLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddLastNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanelPatients.setVisible(false);
        jPanelAddPatient.setVisible(false);
        jPanelAddEmployee.setVisible(false);
        jPanelDirectory.setVisible(false);
        jPanelTerminal.setVisible(false);
        //jPanelWelcome.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientsActionPerformed
        // TODO add your handling code here:
        jPanelPatients.setVisible(true);
        jPanelAddPatient.setVisible(false);
        jPanelAddEmployee.setVisible(false);
        jPanelDirectory.setVisible(false);
        jPanelTerminal.setVisible(false);
        jPanelWelcome.setVisible(false);
        String patientQuery = "SELECT * FROM Patients;";

        PatientTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        QueryExecuter de = new QueryExecuter();
        ResultSet rs = de.runQuery(patientQuery);

        ArrayList<String> empArray = new ArrayList<String>();

        try {
            int columnCount = rs.getMetaData().getColumnCount();
        } catch (SQLException ex) {
            Logger.getLogger(LevelThree.class.getName()).log(Level.SEVERE, null, ex);
        }
        patientModel = (DefaultTableModel) PatientTable.getModel();
        patientModel.setRowCount(0);
        int rowCounter = 1;
        try {
            while (rs.next()) {
                //this adds the next value to the array
                //empArray.add(rs.getString(rowCounter));
                String patientId = rs.getString("PatientID");
                String patientFirstName = rs.getString("FirstName");
                String patientLastName = rs.getString("LastName");
                String patientAllergies = rs.getString("Allergies");
                String patientMedication = rs.getString("Medications");
                String patientPrimaryPhysician = rs.getString("PrimaryPhysician");
                String patientAge = rs.getString("Age");
                String patientGender = rs.getString("Gender");

                //System.out.println(empStaffId + " " + empFirstName + " " + empLastName);
                Object[] row = {patientId, patientFirstName, patientLastName, patientAllergies, patientMedication, patientPrimaryPhysician, patientAge, patientGender};

                patientModel.addRow(row);
                //System.out.println("ID: " + rs.getString(rowCounter));

                //String data1 = rs.getString(rowCounter);              
                //Object[] row = {data1};
                //DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();
                //model.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(LevelThree.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnPatientsActionPerformed

    private static String string;

    /**
     * Get the value of string
     *
     * @return the value of string
     */
    public static String getString() {
        return string;
    }

    /**
     * Set the value of string
     *
     * @param string new value of string
     */
    public static void setString(String string) {
        LevelThree.string = string;
    }

    private void btnDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectoryActionPerformed
        // TODO add your handling code here:
        jPanelPatients.setVisible(false);
        jPanelAddPatient.setVisible(false);
        jPanelAddEmployee.setVisible(false);
        jPanelDirectory.setVisible(true);
        jPanelTerminal.setVisible(false);
        jPanelWelcome.setVisible(false);

        String firstnameQuery = "SELECT * FROM Staff;";

        EmployeeTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        QueryExecuter de = new QueryExecuter();
        ResultSet rs = de.runQuery(firstnameQuery);

        ArrayList<String> empArray = new ArrayList<String>();

        try {
            int columnCount = rs.getMetaData().getColumnCount();
        } catch (SQLException ex) {
            Logger.getLogger(LevelThree.class.getName()).log(Level.SEVERE, null, ex);
        }
        employeeModel = (DefaultTableModel) EmployeeTable.getModel();
        employeeModel.setRowCount(0);
        int rowCounter = 1;
        try {
            while (rs.next()) {
                //this adds the next value to the array
                //empArray.add(rs.getString(rowCounter));
                String empStaffId = rs.getString("StaffID");
                String empFirstName = rs.getString("FirstName");
                String empLastName = rs.getString("LastName");
                String empSignedIn = rs.getString("SignedIn");
                String empTitle = rs.getString("Title");
                String empLevel = rs.getString("Level");
                String empUserName = rs.getString("UserName");
                String empEmail = rs.getString("Email");

                //System.out.println(empStaffId + " " + empFirstName + " " + empLastName);
                Object[] row = {empStaffId, empFirstName, empLastName, empSignedIn, empTitle, empLevel, empUserName, empEmail};

                employeeModel.addRow(row);
                //System.out.println("ID: " + rs.getString(rowCounter));

                //String data1 = rs.getString(rowCounter);              
                //Object[] row = {data1};
                //DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();
                //model.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(LevelThree.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDirectoryActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCloseAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseAllActionPerformed
        // TODO add your handling code here:
        jPanelPatients.setVisible(false);
        jPanelAddPatient.setVisible(false);
        jPanelAddEmployee.setVisible(false);
        jPanelDirectory.setVisible(false);
        jPanelTerminal.setVisible(false);
        jLayeredPaneMainWindow.setVisible(true);
        //jPanelWelcome.setVisible(false);

    }//GEN-LAST:event_btnCloseAllActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEmployeeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeAddActionPerformed
        // TODO add your handling code here:
        jPanelPatients.setVisible(false);
        jPanelAddPatient.setVisible(false);
        jPanelAddEmployee.setVisible(true);
        jPanelDirectory.setVisible(false);
        jPanelTerminal.setVisible(false);
        jPanelWelcome.setVisible(false);

////        if (EmployeeTable.getSelectedRow() != -1) {
////            // remove selected row from the model
////            int valrow  = EmployeeTable.getSelectedRow();
////            
////            Object objID = EmployeeTable.getValueAt(valrow, 0);
////            Object objfName = EmployeeTable.getValueAt(valrow, 1);
////            Object objlName = EmployeeTable.getValueAt(valrow, 2);
////            //Object objPassword = EmployeeTable.getValueAt(valrow, 3);
////            Object objSignedIn = EmployeeTable.getValueAt(valrow, 3); 
////            Object objTitle = EmployeeTable.getValueAt(valrow, 4); 
////            Object objLevel = EmployeeTable.getValueAt(valrow, 5);
////            Object objUsername = EmployeeTable.getValueAt(valrow, 6);
////            
////            
////            System.out.print(objID.toString());
////            System.out.print(objfName.toString());
////            System.out.print(objlName.toString());
////            System.out.print(objSignedIn.toString());
////            System.out.print(objTitle.toString());
////            System.out.print(objLevel.toString());
////            System.out.println(objUsername.toString());
////            
////           // System.out.println("INSERT INTO Customers (CustomerName, ContactName, Address, City, PostalCode, Country")
////            //VALUES ('Cardinal', 'Tom B. Erichsen', 'Skagen 21', 'Stavanger', '4006', 'Norway');
////            System.out.println("DELETE FROM Staff" + "\n" + "WHERE StaffID = " + objID.toString() + ";");
////            
////            employeeModel.removeRow(EmployeeTable.getSelectedRow());
////            System.out.println("row should be removed");
////            
////        }
    }//GEN-LAST:event_btnEmployeeAddActionPerformed

    private void btnDeletePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePatientActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

        if (PatientTable.getSelectedRow() != -1) {
            // remove selected row from the model
            //patientModel.removeRow(PatientTable.getSelectedRow());

            // remove selected row from the model
            int valrow = PatientTable.getSelectedRow();

            Object objID = PatientTable.getValueAt(valrow, 0);

            try {
                // TODO add your handling code here:
                // create a Statement from the connection
                Statement statement = con.createStatement();
                String removePatientQuery = "DELETE FROM Patients WHERE PatientID = " + objID.toString() + ";";
                //String test = textAddFirstName.getText();
                System.out.println("DELETE FROM Patients WHERE PatientID = " + objID.toString() + ";");
                statement.executeUpdate(removePatientQuery);
                System.out.println("Executed");
            } catch (SQLException ex) {
                Logger.getLogger(LevelThree.class.getName()).log(Level.SEVERE, null, ex);
            }
            //QueryExecuter de = new QueryExecuter();
            //ResultSet rs = de.runQuery(con, addUserQuery);
            //System.out.println(rs.toString());

        }
    }//GEN-LAST:event_btnDeletePatientActionPerformed

    private void btnEmployeeRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeRemoveActionPerformed
        // TODO add your handling code here:
        if (EmployeeTable.getSelectedRow() != -1) {
            // remove selected row from the model
            int valrow = EmployeeTable.getSelectedRow();

            Object objID = EmployeeTable.getValueAt(valrow, 0);
            Object objfName = EmployeeTable.getValueAt(valrow, 1);
            Object objlName = EmployeeTable.getValueAt(valrow, 2);
            //Object objPassword = EmployeeTable.getValueAt(valrow, 3);
            Object objSignedIn = EmployeeTable.getValueAt(valrow, 3);
            Object objTitle = EmployeeTable.getValueAt(valrow, 4);
            Object objLevel = EmployeeTable.getValueAt(valrow, 5);
            Object objUsername = EmployeeTable.getValueAt(valrow, 6);

//            System.out.print(objID.toString());
//            System.out.print(objfName.toString());
//            System.out.print(objlName.toString());
//            System.out.print(objSignedIn.toString());
//            System.out.print(objTitle.toString());
//            System.out.print(objLevel.toString());
//            System.out.println(objUsername.toString());
            System.out.println("DELETE FROM Staff WHERE StaffID = " + objID.toString() + ";");
            ////////////////////////////////////////////////////////////////////////////////////////
            try {
                // TODO add your handling code here:
                // create a Statement from the connection
                Statement statement = con.createStatement();
                String removeUserQuery = "DELETE FROM Staff WHERE StaffID = " + objID.toString() + ";";
                //String test = textAddFirstName.getText();
                System.out.println("DELETE FROM Staff WHERE StaffID = " + objID.toString() + ";");
                statement.executeUpdate(removeUserQuery);
                System.out.println("Executed");
            } catch (SQLException ex) {
                Logger.getLogger(LevelThree.class.getName()).log(Level.SEVERE, null, ex);
            }

            //employeeModel.removeRow(EmployeeTable.getSelectedRow());
            System.out.println("row should be removed");

        }
    }//GEN-LAST:event_btnEmployeeRemoveActionPerformed

    private void textAddFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddFirstNameActionPerformed

    private void textAddTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddTitleActionPerformed

    private void textAddLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddLevelActionPerformed

    private void textAddUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddUsernameActionPerformed

    private void btnSaveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUserActionPerformed
        try {
            // TODO add your handling code here:
            // create a Statement from the connection
            Statement statement = con.createStatement();
            System.out.println(textAddLastName.getText());
            String addUserQuery = "INSERT INTO Staff (FirstName, LastName, Title, Level, Username, Password, SignedIn, email) VALUES ('" + textAddFirstName.getText() + "','" + textAddLastName.getText() + "','" + textAddTitle.getText() + "','" + textAddLevel.getText() + "','" + textAddUsername.getText() + "','" + textAddPassword.getText() + "','" + "No" + "','" + textAddEmail.getText() + "');";
            //String test = textAddFirstName.getText();
            System.out.println("INSERT INTO Staff (FirstName, LastName, Title, Level, Username, Password, SignedIn, email) VALUES ('" + textAddFirstName.getText() + "','" + textAddLastName.getText() + "','" + textAddTitle.getText() + "','" + textAddLevel.getText() + "','" + textAddUsername.getText() + "','" + textAddPassword.getText() + "','" + "No" + "','" + textAddEmail.getText() + "');");
            statement.executeUpdate(addUserQuery);
            System.out.println("Executed");
        } catch (SQLException ex) {
            Logger.getLogger(LevelThree.class.getName()).log(Level.SEVERE, null, ex);
        }

        EmployeeTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        //QueryExecuter de = new QueryExecuter();
        //ResultSet rs = de.runQuery(con, addUserQuery);
        //System.out.println(rs.toString());
    }//GEN-LAST:event_btnSaveUserActionPerformed

    private void textAddLastName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddLastName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddLastName1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void textAddFirstName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddFirstName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddFirstName1ActionPerformed

    private void textAddAllergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddAllergiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddAllergiesActionPerformed

    private void textAddMedicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddMedicationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddMedicationsActionPerformed

    private void textAddPhysicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddPhysicianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddPhysicianActionPerformed

    private void btnSavePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePatientActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            // create a Statement from the connection
            Statement statement = con.createStatement();
            //System.out.println(textAddLastName.getText());
            String addPatientQuery = "INSERT INTO Patients (FirstName, LastName, Allergies, Medications, PrimaryPhysician, Age, Gender) VALUES ('" + textAddFirstName1.getText() + "','" + textAddLastName1.getText() + "','" + textAddAllergies.getText() + "','" + textAddMedications.getText() + "','" + textAddPhysician.getText() + "','" + textAddAge.getText() + "','" + textAddGender.getText() + "');";
            //String test = textAddFirstName.getText();
            System.out.println("INSERT INTO Patients (FirstName, LastName, Allergies, Medications, PrimaryPhysician, Age, Gender) VALUES ('" + textAddFirstName1.getText() + "','" + textAddLastName1.getText() + "','" + textAddAllergies.getText() + "','" + textAddMedications.getText() + "','" + textAddPhysician.getText() + "','" + textAddAge.getText() + "','" + textAddGender.getText() + "');");
            statement.executeUpdate(addPatientQuery);
            System.out.println("Executed");
        } catch (SQLException ex) {
            Logger.getLogger(LevelThree.class.getName()).log(Level.SEVERE, null, ex);
        }

        EmployeeTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        //QueryExecuter de = new QueryExecuter();
        //ResultSet rs = de.runQuery(con, addUserQuery);
        //System.out.println(rs.toString());

    }//GEN-LAST:event_btnSavePatientActionPerformed

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed
        // TODO add your handling code here:
        jPanelPatients.setVisible(false);
        jPanelAddPatient.setVisible(true);
        jPanelAddEmployee.setVisible(false);
        jPanelDirectory.setVisible(false);
        jPanelTerminal.setVisible(false);
        jPanelWelcome.setVisible(false);

    }//GEN-LAST:event_btnAddPatientActionPerformed

    private void textAddGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddGenderActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        textTerminal.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnRunTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunTerminalActionPerformed
        // TODO add your handling code here:
        String terminalQuery = textTerminal.getText();
        System.out.println(terminalQuery);
        Statement statement;
        QueryExecuter de = new QueryExecuter();//        QueryExecuter de = new QueryExecuter();
//        ResultSet rs = de.runQuery(con, terminalQuery);
//        textTerminal.setText(rs);
        ResultSet rs = de.runQuery(terminalQuery);
        textTerminal.setText("");
        String holder = "";
        try {
            ResultSetMetaData rsmd = rs.getMetaData();
            //System.out.println("querying SELECT * FROM XXX");
            int columnsNumber = rsmd.getColumnCount();
            while (rs.next()) {
                for (int i = 1; i <= columnsNumber; i++) {
                    if (i > 1) {
                        textTerminal.append(",  ");
                    }
                    String columnValue = rs.getString(i);
                    textTerminal.append(columnValue + " " + rsmd.getColumnName(i));
                }
                textTerminal.append("" + "\n");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LevelThree.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRunTerminalActionPerformed

    private void btnMenuTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuTerminalActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        jPanelPatients.setVisible(false);
        //jPanelRecords.setVisible(false);
        jPanelTerminal.setVisible(true);
        jPanelDirectory.setVisible(false);
        //jPanelMyFiles.setVisible(false);
        jPanelWelcome.setVisible(false);
        //        JPanel employeePanel = new JPanel();
        //        employeePanel.setBounds(10, 10, 10, 10);
        //        jPanel2.add(employeePanel);
        //        employeePanel.setVisible(true);
        //        employeePanel.setBackground(Color.gray);
        //        employeePanel.setSize(900, 500);
        //     //   employeePanel.setLayout(jPanel2Layout);
        //        System.out.println("New panel");
        //
    }//GEN-LAST:event_btnMenuTerminalActionPerformed

    private void btnMenuCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCheckoutActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMenuCheckoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JTable PatientTable;
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JMenuItem btnCloseAll;
    private javax.swing.JButton btnDeletePatient;
    private javax.swing.JButton btnDirectory;
    private javax.swing.JMenu btnEdit;
    private javax.swing.JButton btnEmployeeAdd;
    private javax.swing.JButton btnEmployeeRemove;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenu btnFile;
    private javax.swing.JMenuItem btnLogout;
    private javax.swing.JMenuItem btnMenuCheckIn;
    private javax.swing.JMenuItem btnMenuCheckout;
    private javax.swing.JMenuItem btnMenuTerminal;
    private javax.swing.JButton btnPatients;
    private javax.swing.JButton btnRunTerminal;
    private javax.swing.JButton btnSavePatient;
    private javax.swing.JButton btnSaveUser;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPaneMainWindow;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAddEmployee;
    private javax.swing.JPanel jPanelAddPatient;
    private javax.swing.JPanel jPanelBtns;
    private javax.swing.JPanel jPanelDirectory;
    private javax.swing.JPanel jPanelPatients;
    private javax.swing.JPanel jPanelTerminal;
    private javax.swing.JPanel jPanelWelcome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField textAddAge;
    private javax.swing.JTextField textAddAllergies;
    private javax.swing.JTextField textAddEmail;
    private javax.swing.JTextField textAddFirstName;
    private javax.swing.JTextField textAddFirstName1;
    private javax.swing.JTextField textAddGender;
    private javax.swing.JTextField textAddLastName;
    private javax.swing.JTextField textAddLastName1;
    private javax.swing.JTextField textAddLevel;
    private javax.swing.JTextField textAddMedications;
    private javax.swing.JPasswordField textAddPassword;
    private javax.swing.JTextField textAddPhysician;
    private javax.swing.JTextField textAddTitle;
    private javax.swing.JTextField textAddUsername;
    private javax.swing.JTextArea textTerminal;
    // End of variables declaration//GEN-END:variables
}
